//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AiNetStudio {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class mysettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static mysettings defaultInstance = ((mysettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new mysettings())));
        
        public static mysettings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
